# Generated by Django 5.1.3 on 2024-11-17 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='color',
            field=models.CharField(choices=[('white', 'White 🐾'), ('black', 'Black 🐾'), ('orange', 'Orange 🐾'), ('gray', 'Gray 🐾'), ('calico', 'Calico 🐾')], default='white', max_length=20),
        ),
        migrations.AddField(
            model_name='cat',
            name='sexuality',
            field=models.CharField(choices=[('M', 'Male ♂️'), ('F', 'Female ♀️')], default='M', max_length=1),
        ),
    ]
